### Manual inspection of hero prediction and matches
- Sampled 15% of hero test dataset stratified by mbfc
- Inspected judge matches

Conclusion: MOSTLY looks good to me

- Found a problem with ID 479 (wildfire as a hero). Incorrect label, correct 
prediction, incorrect match.

- ID 231 is debatable, but I still consider it a match given the text.

Details below

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os

from dotenv import load_dotenv
import dspy

load_dotenv()

openai_key = os.getenv(
        "OPENAI_API_KEY"
    )

/Users/catherine/Library/Caches/pypoetry/virtualenvs/afan-WLhS1US3-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
from afan.dataset import load_and_preprocess_dataset

hero_test = load_and_preprocess_dataset(
    dataset_name="hero_test",
    data_dir="../data/test/",
    columns=["ID", "mbfc", "text", "entities"]
)

hero_test.head(2)

,ID,mbfc,text,entities
0,804,left_center_bias,Exxon Mobil Lends Its Support to a Carbon Tax ...,"[Carbon tax, The group]"
1,366,right_bias,Mongolians sip 'oxygen cocktails' to cope with...,"[NGOs and Non-profit organisations, Mongolian ..."

In [4]:
hero_test.shape[0]

76

In [29]:
from sklearn.model_selection import train_test_split

# Calculate sample size (25% of total)
sample_size = int(0.25 * hero_test.shape[0])

# Get stratified sample
_, sampled_hero = train_test_split(
    hero_test,
    test_size=0.15,
    stratify=hero_test['mbfc'],
    random_state=42
)

# Display result
print(f"Original size: {hero_test.shape[0]}")
print(f"Sample size: {sampled_hero.shape[0]}")
print("\nMBFC distribution in sample:")
print(sampled_hero['mbfc'].value_counts())

Original size: 76
Sample size: 12

MBFC distribution in sample:
mbfc
left_bias              4
right_bias             3
left_center_bias       3
questionable_source    2
Name: count, dtype: int64

In [30]:
sampled_hero

,ID,mbfc,text,entities
57,78,right_bias,First meat grown in space lab 248 miles from Earth... Lab-grown meat has been successfully cultured in space for the first time. The Israeli food technology startup Aleph Farms grew the meat on th...,"[Lab-grown meat, The Israeli food technology startup Aleph Farms]"
43,690,left_bias,Trump's war on climate policy is also a war on public health Environmental Protection Agency chief Scott Pruitt is expected to sign a proposed rule on Tuesday that would roll back a key piece of P...,"[Obama, Clean Power Plan]"
18,697,left_bias,"California governor declares end to drought emergency LOS ANGELES (Reuters) – One of the worst droughts in California history has officially ended, Governor Jerry Brown declared, but not before it...",[Governor Jerry Brown]
46,847,questionable_source,"California districts sue US govt for $1.4bn over water contamination from military base Two water districts in Sacramento, California are suing the US government for nearly one and a half billion ...",[California water districts]
54,339,right_bias,"All These Climate Change Lawsuits Will Be Thrown Out Last week, a federal judge dismissed New York City's climate change lawsuit against five major oil companies. Last month, another federal judge...","[U.S. Courts, US District Judge William Alsup]"
36,44,right_bias,"Kids Around The World Are Using Climate Change As An Excuse To Skip School Young students across the world plan to skip class on Friday, claiming that they will devote the day to protesting man-ma...",[Climate activists]
71,789,left_center_bias,"EPA wipes its climate change site as protesters march in Washington The US Environmental Protection Agency's main climate change website is ""undergoing changes"" to better reflect ""the agency's new...","[Climate activists, senator]"
16,838,questionable_source,"250,000 Americans, 500 groups reject genetically-modified eucalyptus trees Over 250,000 Americans and 500 organizations submitted comments rejecting the US Department of Agriculture's (USDA) propo...",[Anne Petermann executive director at the Global Justice Ecology Project]
29,177,left_center_bias,"The sea-cooled eco-resort that's nearly mosquito-free The Brando is one of the most luxurious eco-resorts on the planet, nestling on an atoll in the middle of the Pacific Ocean. It's the last plac...",[The Brando]
60,231,left_center_bias,"Global Youth Climate Strike Expected To Draw Large Crowds Spurred by what they see as a sluggish, ineffectual response to the existential threat of global warming, student activists from around th...",[youth climate activism]
33,444,left_bias,"FEMA is preparing for the future. ""Climate change"" isn't part of it. The United States is still reeling from last year's megadisasters. Puerto Rico lingers in the longest blackout in US history af...",[FEMA]
58,674,left_bias,"Judge Rules Dakota Access Pipeline To Continue Operating Amid Impact Study BISMARCK, N.D. (AP) — A federal judge ruled Wednesday that the Dakota Access oil pipeline can continue operating while a ...",[Boasberg]

# Predict: gpt-4o-mini

In [31]:
prediction_lm = dspy.LM("openai/gpt-4o-mini", api_key=openai_key)

dspy.configure(lm=prediction_lm)

In [32]:
from afan.prompts.signatures import NarrativeArcSignature

predictor = dspy.Predict(NarrativeArcSignature)

In [33]:
from afan.utils import predict

hero_preds = predict(
    df=sampled_hero,
    predictor=predictor,
    entity="hero"
    )

hero_preds.head(2)

,ID,mbfc,text,entities,predicted_entity
57,78,right_bias,First meat grown in space lab 248 miles from Earth... Lab-grown meat has been successfully cultured in space for the first time. The Israeli food technology startup Aleph Farms grew the meat on th...,"[Lab-grown meat, The Israeli food technology startup Aleph Farms]","Aleph Farms, the Israeli food technology startup."
43,690,left_bias,Trump's war on climate policy is also a war on public health Environmental Protection Agency chief Scott Pruitt is expected to sign a proposed rule on Tuesday that would roll back a key piece of P...,"[Obama, Clean Power Plan]",The Clean Power Plan and public health advocates.

# Judge

In [34]:
judge_lm = dspy.LM("gpt-4.1-mini", api_key=openai_key)

dspy.configure(lm=judge_lm)

In [35]:
from afan.prompts.judges import EntitiesMatchFewShot

judge_few_shot = dspy.Predict(EntitiesMatchFewShot)

In [36]:
from afan.utils import judge

hero_judged = judge(
    df=hero_preds,
    judge_match=judge_few_shot
)

Accuracy: 75.00%

In [43]:
import pandas as pd

pd.set_option('display.max_colwidth', 200)

cols_to_compare = ["ID", "mbfc", "entities", "predicted_entity", "judge_match"]

In [38]:
# A wildfire as a hero? That's a problem. ID 479


hero_test[hero_test.ID == 479].text.values[0]

'California wildfires: Key questions answered In the last year alone, California has seen catastrophic wildfires burn thousands of acres. On Tuesday, the ongoing Camp Fire in Northern California became the state\'s deadliest blaze in history. How do these deadly fires start, and why is California so susceptible?Officials define wildfires, or wildland fires, as any fire occurring on undeveloped land. Forest fires are uncontrolled wildfires burning in lands covered at least in part by timber or flammable vegetation. In nature, two things can spark wildfires: lava and lightning. According to the National Park Service, 90% of wildfires in the US are caused by humans - whether by unattended campfires, burning debris, cigarettes, or arson. About 2% of California\'s 2,816 wildfires in 2016 were caused by lightning, according to data from the California Department of Forestry and Fire Protection (Cal Fire). The majority could be attributed to humans, though only 8% were caused by arson. According to Prof David Peterson of the University of Washington, a former senior researcher with the US Forest Service, fires in the region have not necessarily increased in frequency in the last 100 years - but the area affected has." The area burned annually has been higher during the past 30 years or so," he told the BBC. "It should be noted that 2% of fires burn 98% of the area." In California, recent years have seen a combination of extremely high temperatures, strong winds, a long drought, and population growth causing lethal, fast-moving blazes. Last year, the state had over 9,500 wildfires that burned over a million acres, according to the National Interagency Fire Center, and had the highest number of homes and buildings lost in one state. And straying away from natural burning cycles has also contributed to the lethality of recent fires, Prof Peterson says. Keeping fires from starting in Western forests has caused fuel to accumulate "far beyond" historical levels." Therefore, when fires occur they can burn hotter," he says. "These high-intensity fires can cause rapid and in some cases long-term changes in vegetation, making it more difficult for the ecosystem to recover." Once evacuation orders are issued by local law enforcement, residents generally have hours to leave, Cal Fire information officer Kathleen Schori told the BBC." But in those initial stages of fire, you may have minutes," she added. Fleeing in a vehicle is ideal as most wildfires cannot be outrun. But the Camp Fire\'s especially rapid spread, fuelled by high winds, made the situation even more dangerous." This fire moved so fast - I don\'t think anybody did anything wrong," Ms Schori says when asked whether those forced to abandon vehicles and escape on foot could have acted differently." During the initial phases, it was burning 80 miles in an hour." She stressed the importance of following evacuation orders immediately, especially with fast-moving blazes." If you don\'t evacuate and it becomes a rescue situation, then our firefighters are taken away from the firefight and moved to the rescue." Sometimes, you do fight fire with fire. In addition to old-fashioned water and flame retardant (delivered from ground-level and above the flames by aircraft), sometimes firefighters have to burn more to quell the flames. Intentionally burning areas around a wildfire can help starve the blaze and control its direction. Clearing out brush and flammable material from an area to create "firebreaks" is another way to achieve the same." Ninety-eight percent of fires are small and/or suppressed quickly," Prof Peterson says. "The other 2% are very challenging when they get large, and are almost impossible to put out, at least until it rains." Ms Schori of Cal Fire said that with wind-driven blazes like the Camp Fire, officials often have no choice but to wait for conditions to improve." There are never enough firefighters to combat a fire that\'s moving as fast as this was moving," she says." You have to deploy your resources on each side [of the fire] and continue to construct lines. And when that wind stops, then you can safely get in front it." Prof Peterson says there is no hard evidence that climate change has affected US wildfires - yet." We expect that there will be significant effects in future decades as the climate continues to warm," he told the BBC. A warming climate, Prof Peterson explained, would increase the duration of the fire season, and more droughts would in turn create more wildfire fuel. Globally, the length of the wildfire season has already increased by nearly 19% between 1978 and 2013." By around 2050, fires may burn two to three times more area than they have historically." According to 2017 data from Verisk Analytics, 4.5 million US homes were in areas of high or extreme wildfire risk - and over 2 million of those homes were in California. Damage caused by wildfires has cost $5.1bn in the last decade, Verisk found. In California, homeowners who do not qualify for private insurance coverage can opt into a statewide pool, called the Fair Access to Insurance Requirements (FAIR) plan. FAIR is comprised of all property and casualty insurers in California and is not run by a state agency.'

In [ ]:
hero_judged[hero_judged.ID == 479]

In [ ]:
# debatable: ID 231. But I still think it's correct given the text


hero_test[hero_test.ID == 231].text.values[0]

'Global Youth Climate Strike Expected To Draw Large Crowds Spurred by what they see as a sluggish, ineffectual response to the existential threat of global warming, student activists from around the world plan to skip school today for what organizers call a Global Climate Strike. The focus for young activists is the United Nations Climate Action Summit taking place Monday in New York City. The strike\'s figurehead is 16-year-old Swedish activist Greta Thunberg, who traveled from Sweden to New York on an emission-free sailboat. A little over a year ago Thunberg began her school strike for the climate, by herself, outside the Swedish Parliament. Support for a school climate strike has since spread across the globe. In the last year Thunberg has been nominated for the Nobel Peace Prize by Norwegian lawmakers. She\'s also met with Pope Francis and lawmakers in several countries." We are currently on track for a world that could displace billions of people from their homes," Thunberg warned this week during a speech accepting Amnesty International\'s Ambassador of Conscience Award. She ended her acceptance speech with a call to action: "See you on the streets!"In New York City thousands of students may fill the streets with Thunberg because, as the school district announced on Twitter, it is giving strikers excused absences. In Oregon Portland Public Schools is doing the same. Strikes also are planned in rural areas where just a few dozen protesters are expected. Nicholas DuVernay, 17, organized a protest in his politically-conservative small town of La Grande, Ore." Since, probably, the beginning of my junior year in high school I\'ve been interested in climate science and pretty passionate about environmental topics," says DuVernay, who plans to study climate science when he attends college next year. A Washington Post-Kaiser Family Foundation poll this week shows a majority of teenagers believe human-caused climate change will cause harm to them. And a quarter of the poll respondents said they have participated in a school walk-out, a rally or contacted a government official on the issue. There have been similar student events in the past year. But this time students are asking adults to join them. At the University of Nevada, Reno, Stallar Lufrano-Jardine, 36, is setting up an event on campus where she\'s an employee and student."I\'m bothered by the lack of movement to make meaningful advances to solve the climate crisis," says Lufrano-Jardine. But it\'s clear younger people are leading this movement and they say most adults — especially policy-makers — are moving far too slowly. Strike organizers have a list of demands that includes "respect of indigenous land, sustainable agriculture, protecting biodiversity, environmental justice and a just transition away from fossil fuels and towards renewable energy," said 17-year-old Baltimore resident and organizer Nadia Nazar. Many of those demands are part of the Green New Deal, which was crafted by progressive Democratic lawmakers but so far hasn\'t gone anywhere in Congress. At a Capitol Hill press event this week Nazar said she hopes the proposal defines her generation. "I am not a part of Generation Z. I am a part of Gen GND — the generation of the Green New Deal," said Nazar as supporters cheered. Also on Capitol Hill this week, Thunberg and other activists testified before lawmakers. Louisiana Republican Rep. Garret Graves told them climate change has exacerbated the loss of his state\'s coastline."I agree that we need to take aggressive action. I agree that we need to ensure that we move forward in a sustainable, rational manner," said Graves. But his idea of what that means is very different than the activists\' vision. Graves agrees with President Trump on the need to withdraw from the Paris climate agreement. Graves told the student organizers the pact allows China to continue emitting more carbon dioxide while the U.S. cuts emissions. "Paris and its related pledges would undermine U.S. competitiveness," his spokesman said. Graves got immediate push-back from the young activists, including 17-year-old Jamie Margolin from Seattle who asked how Graves will respond to questions from his children and grandchildren about whether he did enough to address climate change." Can you really look them in the eye and say, \'No, sorry, I couldn\'t do anything because that country over there didn\'t do anything, so if they\'re not going to do it then I\'m not.\' That is shameful and that is cowardly," Margolin said. Organizers predict this climate strike will be the largest yet. More than 2000 scientists around the world have pledged to join. Some companies also have signed on, including Patagonia and Seventh Generation.'

In [46]:
hero_judged[cols_to_compare]

,ID,mbfc,entities,predicted_entity,judge_match
57,78,right_bias,"[Lab-grown meat, The Israeli food technology startup Aleph Farms]","Aleph Farms, the Israeli food technology startup.",True
43,690,left_bias,"[Obama, Clean Power Plan]",The Clean Power Plan and public health advocates.,True
18,697,left_bias,[Governor Jerry Brown],California residents who adapted their water usage to combat the drought.,False
46,847,questionable_source,[California water districts],Sacramento Suburban Water District and Rio Linda Elverta Community Water District,True
54,339,right_bias,"[U.S. Courts, US District Judge William Alsup]",The federal judges who dismissed the lawsuits.,True
36,44,right_bias,[Climate activists],Youth activists,True
71,789,left_center_bias,"[Climate activists, senator]","The protesters and climate activists, including notable figures like Al Gore and Leonardo DiCaprio, advocating for climate justice.",True
16,838,questionable_source,[Anne Petermann executive director at the Global Justice Ecology Project],Activists and environmental organizations advocating for ecological safety.,False
29,177,left_center_bias,[The Brando],The Brando eco-resort.,True
60,231,left_center_bias,[youth climate activism],Greta Thunberg,True
33,444,left_bias,[FEMA],FEMA (as an agency),True
58,674,left_bias,[Boasberg],Standing Rock Sioux tribe,False

In [45]:
hero_judged[cols_to_compare][hero_judged.judge_match==False]

,ID,mbfc,entities,predicted_entity,judge_match
18,697,left_bias,[Governor Jerry Brown],California residents who adapted their water usage to combat the drought.,False
16,838,questionable_source,[Anne Petermann executive director at the Global Justice Ecology Project],Activists and environmental organizations advocating for ecological safety.,False
58,674,left_bias,[Boasberg],Standing Rock Sioux tribe,False